### ISSUE TITLE
PV modules issue

### ISSUE THREAD

**Issue by jeremycruz82** [peterpeerdeman/rasplogger#2]
Hi, First off I appreciate the work you have done here. I am getting started in SOLAR and have been trying to find a way to get some data that is currently in PVoutput over into InfluxDB. I ran across your page and it seems to be exactly what I am looking for. I tried running node rasplogger.js cron pv "*/5 * * * *" -u http://localhost:8086/pv , however I receive the below. Can you please advise how I can fix this? Also I tried inputting the API and System ID, however when I do I get the error unauthorized 401 or invalid token. 

2020-09-04T13:55:48.980Z RaspLogger activated module pv
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: Unauthorized 401: Invalid System ID, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/home/pi/rasplogger/node_modules/moment/moment.js:320:98)
    at configFromString (/home/pi/rasplogger/node_modules/moment/moment.js:2385:15)
    at configFromInput (/home/pi/rasplogger/node_modules/moment/moment.js:2611:13)
    at prepareConfig (/home/pi/rasplogger/node_modules/moment/moment.js:2594:13)
    at createFromConfig (/home/pi/rasplogger/node_modules/moment/moment.js:2561:44)
    at createLocalOrUTC (/home/pi/rasplogger/node_modules/moment/moment.js:2648:16)
    at createLocal (/home/pi/rasplogger/node_modules/moment/moment.js:2652:16)
    at hooks (/home/pi/rasplogger/node_modules/moment/moment.js:12:29)
    at /home/pi/rasplogger/node_modules/pvoutput/pvoutput.js:91:23
    at tryCatcher (/home/pi/rasplogger/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/rasplogger/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/pi/rasplogger/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/pi/rasplogger/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/pi/rasplogger/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/pi/rasplogger/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/pi/rasplogger/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/pi/rasplogger/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/rasplogger/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

**Comment by peterpeerdeman** [comment]
Hi @jeremycruz82 ! So terribly sorry for not replying to this earlier, I didn't receive a notification for this issue. It's probably a bit late but I still want to answer. It looks like the credentials for the PV module are not set correctly. Have you created a .env file in the root of the project containing something like:

```
PVOUTPUT_APIKEY=xxxxx
PVOUTPUT_SYSTEMID=xxxxx
```

just like the .env.example file but in a separate .env file? The error code suggests that the script has not detected a proper api key and therefore gives an 401 unauthorized string instead of actual data.

**Comment by peterpeerdeman** [comment]
I've updated the documentation to explain the use of the .env file: https://github.com/peterpeerdeman/rasplogger/commit/d62f6c531da4ded01f75170512388cb47b2d8a6a
